### ISSUE TITLE
Release for arm64 architecture ?

### ISSUE THREAD

**Issue by rfenouil** [mrene/minidsp-rs#198]
Hello and thank you for the great work !

I have been trying to install your program on a rock64 device with [Ayufan linux build](https://github.com/ayufan-rock64/linux-build) but the architecture is declared as `arm64` instead of `armhf` so it fails with following error message:

```
>dpkg -i minidsp_0.1.2_armhf.deb
dpkg: error processing archive minidsp_0.1.2_armhf.deb (--install):
 package architecture (armhf) does not match system (arm64)
```

I tried to install cargo and compile the project but I get various build errors for external libraries (`riff`, `urlencoding`, `bimap`, ...).
I never used rust so I cannot debug it properly to get the build done.

Would it be possible to provide an `arm64` release too ?
If not, can you provide some instructions on how to build the project ?

Thank you !

**Comment by mrene** [comment]
I can look into adding arm64 builds into github actions. Did you install rust with `rustup` (like in [the instructions](https://minidsp-rs.pages.dev/getting-started#building-from-source))? Distros often have outdated rust versions which doesn't build recent packages.

**Comment by rfenouil** [comment]
My apologies, I missed this part in the instructions... Got it working with `rustup` !
You are correct, errors were related to an outdated rust version in official repositories...

Thank you for your help.

**Comment by mrene** [comment]
@younger38 try this build https://github.com/mrene/minidsp-rs/releases/download/v0.1.4/minidsp_0.1.4_arm64.deb

**Comment by younger38** [comment]
Wow thanks @mrene I was able to compile it myself eventually however its still clunky The new released arm64 worked like a charm, thanks so much for doing this and so quickly.
