### ISSUE TITLE
.deb installs executable in /usr/bin, but minidsp.service expects it in /usr/local/bin

### ISSUE THREAD

**Issue by linerjoe** [mrene/minidsp-rs#22]
The .deb installs the minidsp executable in /usr/bin, but the minidsp.service references /usr/local/bin.

$ which minidsp
/usr/bin/minidsp

Jan 12 19:37:38 server systemd[1009]: minidsp.service: Failed to execute command: No such file or directory
Jan 12 19:37:38 server systemd[1009]: minidsp.service: Failed at step EXEC spawning /usr/local/bin/minidsp: No such file or directory
Jan 12 19:37:38 server systemd[1]: minidsp.service: Main process exited, code=exited, status=203/EXEC
Jan 12 19:37:38 server systemd[1]: minidsp.service: Failed with result 'exit-code'.
Jan 12 19:37:39 server systemd[1]: minidsp.service: Scheduled restart job, restart counter is at 5.

Service starts fine once I moved the file to /usr/local/bin.

**Comment by mrene** [comment]
Oh good catch I'll fix that!
