### ISSUE TITLE
Config change hangs client

### ISSUE THREAD

**Issue by conrad-nash** [mrene/minidsp-rs#26]
Hi,

Another issue :)

It looks like the minidsp is sending back an ambiguous response when attempting to change the config.
When I execute `minidsp --tcp 192.168.86.40:5333 config 0` from my windows 10 PC to my pi, both running 0.0.3 I get the following in my Pi log:

````
New connection: 192.168.86.54:65079
Sent: SetConfig { config: 00, reset: true } 
Recv: MaybeConfigChanged
````

And the command on the PC hangs. This happens whether I set the config to the same as current, or a different config.

It also works with a local, directly connected set-up.

Let me know if you need more info

Thanks

**Comment by mrene** [comment]
Fixed in [0.0.4](https://github.com/mrene/minidsp-rs/releases/tag/v0.0.4)
