### ISSUE TITLE
Feature request: master mute toggle

### ISSUE THREAD

**Issue by lasselukkari** [mrene/minidsp-rs#356]
Thank a lot for the awesome project! I use it on a daily basis to control my home stereo setup.

For similar reasons the relative gain feature was introduced I would like to be able to toggle the master mute setting. I have a rotary encoder based volume knob that emulates a keyboard. I would like to be able to toggle the master mute regardless of the current state by pressing the knob.

**Comment by lasselukkari** [comment]
If you think the feature makes sense I can create a pull request myself.

**Comment by mrene** [comment]
Hi! I think it makes sense, there's already command to change the master volume relative to the current one.

Did you plan on adding this to the command line interface or to the http api?

**Comment by lasselukkari** [comment]
The command line interface.

**Comment by lasselukkari** [comment]
How would you like it to work? Should I just extend the existing `on` and `off` parameters with `toggle` or do you have a better idea?

**Comment by mrene** [comment]
Having `toggle` as a value alongside `on` and `off` seems simple enough.

**Comment by lasselukkari** [comment]
Got it working. Should I do the same change for the Dirac setting as well?

**Comment by mrene** [comment]
Yeah toggling dirac would make sense too. 

I'm curious - what volume knob are you using?

**Comment by lasselukkari** [comment]
It's this one: https://www.doukaudio.com/products/black-all-metal-usb-volume-controller-lossless-audio-vol-adjuster-for-window-mac-134. I paid 25$ including postage for it. The rotary encoder feels a bit cheap but so far it's been working fine.

**Comment by lasselukkari** [comment]
Done in #359.
