### ISSUE TITLE
Provide machine readable status output

### ISSUE THREAD

**Issue by 3ll3d00d** [mrene/minidsp-rs#39]
current output is easy to read but fiddly to parse, an option to format this output in some way would be useful e.g.

`minidsp -o json`

would provide the same output but as a json document

**Comment by mrene** [comment]
Are you looking at other things except master status?

I have this in progress:

```json
{
  "master": {
    "preset": 0,
    "source": "Toslink",
    "volume": -25.0,
    "mute": false
  },
  "available_sources": [
    "Analog",
    "Toslink",
    "Usb"
  ],
  "input_levels": [
    -131.42198,
    -131.42198
  ],
  "output_levels": [
    -157.00223,
    -166.65083,
    -120.0,
    -120.0
  ]
}
```

**Comment by 3ll3d00d** [comment]
atm the only value I read is  `master.preset`

**Comment by mrene** [comment]
0.0.5 has `-o json` which pretty prints the above json, or `-o jsonline` which prints it on a single line, which should be easier to parse.

If you're keeping an open subprocess, I added a `status` command, just run it as `minidsp -o jsonline -f -` and it'll echo back the json object.

I have to look at this http interface next :)
