### ISSUE TITLE
EzBeq.clearSlot failed, HTTP status 500 error with 0.1.8

### ISSUE THREAD

**Issue by luv2fly3** [mrene/minidsp-rs#479]
I downloaded 0.1.8 and now am getting a "EzBeq.clearSlot failed, HTTP status 500" every time I try to make a change using EZBeq. SSH session with a "minidsp" command shows my 2x4HD as connected. I even just reset my Pi and did a clean install wondering if something was messed up on it. But I am still seeing that error even after a complete new installation of Raspian, minidsp-rs and EZBeq.

On my SSH session I see this info at the end of the process..

"raise ProcessExecutionError(

plumbum.commands.processes.ProcessExecutionError: Unexpected exit code: 1

Command line: | /usr/bin/minidsp -f /tmp/tmpw3kolc2o

Stderr: | While executing: input 0 peq 0 bypass off

| error: The argument '[VALUE]' requires 0 values, but 1 was provided

|

| Usage: minidsp input peq <INDEX> bypass [VALUE]

|

| For more information try '--help'

|

| Error: Command failure
"

Not sure if there is any information in that data that can point to what is occurring? I downgraded back to v0.1.7 and EZBeq started working just fine again. Not sure if I missed something, but .8 doesn't work for me.

**Comment by mrene** [comment]
Thanks for the report! Seems to be an issue with the library used to parse the commands. Will be fixed in 0.1.9.
