### ISSUE TITLE
cargo.lock out of date

### ISSUE THREAD

**Issue by adamcstephens** [mrene/minidsp-rs#484]
The Cargo.lock in release 0.1.9 is out of date. https://github.com/mrene/minidsp-rs/blob/v0.1.9/Cargo.lock#L566

I'm building a Nix package for minidsp-rs, and it is complaining about this. I can patch around it, but wanted to let you know that it got missed in the latest release. Thanks!

**Comment by mrene** [comment]
Thanks! I I'll make sure to add `cargo update` to the release ritual. Patched `dev` for now.
