### ISSUE TITLE
Check with DeviceControl Software Update

### ISSUE THREAD

**Issue by holisticagile** [mrene/minidsp-rs#568]
Hey,

did anybody check compatibility with new Devices Control Software from minidsp?
Would love to clarify before updating and breaking the connection for minidsp-rs
thy

**Comment by scottshanafelt** [comment]
I think you are refering to device console?  I did upgrade my SHD to that latest firmware.  While minidsp-rs works in every way I've tried with it, the ability for device console to "tunnel" through minidsp-rs directly to the SHD does not work.  Device Console throws some error when I attempt to connect.  The MiniDSP android app does continue to work.

**Comment by holisticagile** [comment]
ok, cool. Thank you for your reply.
I would not like to loose the ability to control via. api my minidsp. :)
