### ISSUE TITLE
Only basic functionality work by fact on MiniDSP DDRC24 and 2x4HD

### ISSUE THREAD

**Issue by DenDeXTeR51** [mrene/minidsp-rs#609]
I use latest build + DDRC24/2x4HD (MCU 1.61, DSP 1.6) + WifiDG and only basic settings can be changed like (Master Settings, Gain, mute, etc) using cli. All other changes like outputs/inputs settings dont work by fact. 

Works only = "minidsp gain", "minidsp mute", etc 

Dont work = "minidsp output 3 gain -- -20", and everything that is related to inpust/output

What can be wrong?

**Comment by mrene** [comment]
The official applications don't read state from the device, so the settings get changed, but they don't get reflected in their user interface. That's a limitation of the way the firmware is designed.

The exception to this rule are the master gain / volume, current preset and source selection, which you do see as reflected.
