### ISSUE TITLE
mock devices do not seem to work

### ISSUE THREAD

**Issue by iloveicedgreentea** [mrene/minidsp-rs#683]
I uncommented the supplied mock options but every invocation of `minidsp` results in `no devices found`

[[static_device]]
url = "mock:?serial=922222"

**Comment by mrene** [comment]
The configuration file is only read by the daemon, if you want to use mock devices with the main `minidsp` command without the daemon, you can use `minidsp --url` or set the `MINIDSP_URL` environment variable.

```
❯ MINIDSP_URL='mock:?serial=922222' minidsp probe
0: Found 2x4HD with serial 922222 at mock:?serial=922222 [hw_id: 10, dsp_version: 100]
```

You could also start the daemon and `minidsp` will then connect to it via a local unix socket

```
❯ cat config.toml
[[static_device]]
url = "mock:?serial=922222"

❯ minidspd -c ./config.toml &
App is running on: 0.0.0.0:5380
App is listening on: /tmp/minidsp.sock

✦ ❯ minidsp probe
0: Found 2x4HD with serial 922222 at ws://localhost/devices/0/ws [hw_id: 10, dsp_version: 100]
```
