### ISSUE TITLE
SHD support

### ISSUE THREAD

**Issue by FeathersMcG** [mrene/minidsp-rs#90]
Hi,

Here is the information you requested for minidsp-rs connected 
to a miniDSP SHD.  This is a SHD (not SHD Studio or Power) 
purchased about August or September of 2019.  The host connected 
to the SHD and running minidsp-rs is a RPi 4B 8GB running the 
32 bit version of RPi OS Buster.  Versions of the miniDSP plugin 
for Windows and SHD firmware are 1.15 and 1.29, respectively.  

Attached are the saved configuration XML file from the Windows 
plugin and zipped directory tree.  The directory tree has the output 
produced by the various commands you requested plus a few extra.  
Also included is the content yielded by cating the various files 
located in and below /proc/asound/SHD/.  

Let me know if you need any additional information.  Thanks 
again for creating minidsp-rs.  

Cheers
Feathers

[Configuration.xml.zip](https://github.com/mrene/minidsp-rs/files/6256503/Configuration.xml.zip)
[SHD.zip](https://github.com/mrene/minidsp-rs/files/6256504/SHD.zip)

**Comment by mrene** [comment]
Thanks for this - I've added experimental support for the SHD in [0.1.0](https://github.com/mrene/minidsp-rs/releases/tag/v0.1.0) - I don't have one of these to test, so feel free to open an issue if something feels wrong.
